name: Build & Push Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        name: Check out code
        with:
          submodules: recursive

      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bot
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/gridscout/gridscout:latest
          platforms: linux/amd64
          build-args: COMMIT_HASH=${{ github.sha }}
          context: .
          file: ./apps/bot/Dockerfile
          cache-from: type=gha,scope=bot
          cache-to: type=gha,scope=bot,mode=max

      - name: Build and push cron
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/gridscout/cron:latest
          platforms: linux/amd64
          build-args: COMMIT_HASH=${{ github.sha }}
          context: .
          file: ./apps/cron/Dockerfile
          cache-from: type=gha,scope=cron
          cache-to: type=gha,scope=cron,mode=max
